history/urls.py
# from django.conf.urls import url, include
from django.urls import path, include
from history.views import *

app_name = "history"

urlpatterns = [
    path('', historyIndex.as_view(), name='index'),
    # url(r'^test/', testIndex.as_view())
]

history/models.py
from django.db import models
from portfolio.models import PortfolioGroup

# Create your models here.
class History(models.Model):
	title = models.CharField(max_length=255, null=True)
	group = models.ForeignKey(PortfolioGroup, verbose_name="년도", null=True, on_delete=models.CASCADE)
	create_date = models.DateTimeField('Create Date', auto_now_add=True, null=True)

	class Meta:
		verbose_name_plural = '연혁'
	
	def __str__(self):
		return self.title

history/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.http import response
from django.http import HttpResponse
from history.models import History
from portfolio.models import PortfolioGroup
from django.conf import settings

# Create your views here.

class historyIndex(ListView):
	model = PortfolioGroup
	context_object_name = 'historyIndex'
	template_name = 'history/history_index.html'
	css_version = 8
	ordering = ['name']
	page_title = '연혁 | '+settings.SITE_NAME

	# def get(self, request, *args, **kwargs):
	# 	context = self.get_context_data(**kwargs)
	# 	response = self.render_to_response(context)
	# 	response.set_cookie('test2', 'tetete3')
	# 	return response

	def get_context_data(self, **kwargs):
		ctx = super(historyIndex, self).get_context_data(**kwargs)
		ctx['category'] = 'history'
		ctx['css_version'] = self.css_version
		ctx['page_title'] = self.page_title

		return ctx


class testIndex(ListView):
	model = History
	template_name = 'history/test.html'
		

history/templates/history/history_index.html
{% extends "base.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/history.css" %}?v={{ css_version }}{% endblock %}

{% load portfolio_filters %}
{% block content %}
<div class="bg bg2"></div>
<div class="content-bottom-not-space" id="content">
	<div class="history">
		<div class="line"></div>
		{% for year in historyIndex %}
		{% if year.history_set.count > 0 %}
		<div class="history-list">
			<div class="history-year {{ year.id|year_position:'circle' }}">{{ year.name }}</div>
			<div class="history-detail {{ year.id|year_position:'line' }}">
				<div class="line"></div>
				<div class="line-finish"></div>
				{% for history in year.history_set.all %}
				<div class="history-detail-list {{ year.id|year_position:'list' }}">{{ history.title }}</div>
				{% endfor %}	
			</div>
		</div>
		{% endif %}
		{% endfor %}
	</div>

	<div class="company-info">
		<div>부산시 해운대구 센텀중앙로 55 <br>동서대학교 센텀캠퍼스 612호</div>
		<div>010-9983-5106</div>
		<div>goodboypic@gmail.com</div>
	</div>
</div>
{% endblock %}

history/templates/history/test.html
{% extends "base.html" %}

{% block title %}연혁{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/history.css" %}?v={{ css_version }}{% endblock %}

{% load portfolio_filters %}
{% block content %}
<style>

	.bg4:before{
		content: "";
		display: block;
		position: fixed;
		left: 0;
		top: 0;
		width: 100%;
		height: 100%;
		z-index: -10;
		background: url(/static/images/bg1_m.jpg) no-repeat center 0px;
	}
</style>
<div class="bg bg4"></div>
<div id="content">
	<div style="height: 1000px;"></div>
</div>
{% endblock %}