portfolio/urls.py
from django.urls import path, re_path
from portfolio.views import *
from django.http import HttpResponse

app_name = "portfolio"

urlpatterns = [
    path('', PortfolioGroupLV.as_view(), name='index'),
    re_path('(?P<slug>[\w-]+)/', PortfolioGroupDV.as_view(), name='portfolio_detail'),
    # path('<slug:slug>/', PortfolioGroupDV.as_view(), name='portfolio_detail'),
    # url(r'^portfolio-group/(?P<pk>\d+)/$', PortfolioGroupLV.as_view(), name='portfolio_group_detail'),
]

portfolio/models.py
from django.db import models
from django.urls import reverse
from portfolio.fields import ThumbnailImageField
from accounts.models import User
from django.utils.text import slugify


# Create your models here.
class PortfolioGroup(models.Model):
	name = models.CharField(max_length=50, null=True)
	description = models.CharField('One Line Description', max_length=100, blank=True)

	class Meta:
		verbose_name_plural = '년도'
		ordering = ['-name']

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('portfolio:portfolio_group_detail', args=(self.id,))

		


class Portfolio(models.Model):
	group = models.ForeignKey(PortfolioGroup, verbose_name="년도", on_delete=models.CASCADE)
	title = models.CharField('제목', max_length=50)
	slug = models.SlugField('SLUG', unique=True, allow_unicode=True, null=True, help_text='자동 입력')
	image = ThumbnailImageField(verbose_name="대표 이미지", upload_to='portfolio/%Y/%m', blank=True, null=True)
	description = models.TextField('DESCRIPTION', blank=True)
	link = models.URLField('link', blank=True)
	upload_date = models.DateTimeField('작성일', auto_now_add=True)
	user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = '포트폴리오'
		ordering = ['-upload_date']

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('portfolio:portfolio_detail', args=(self.slug,))


	def save(self, *args, **kargs):
		if not self.id:
			self.slug = slugify(self.title, allow_unicode=True)
		super(Portfolio, self).save(*args, **kargs)

portfolio/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from portfolio.models import *
from home.lib.parseurl import urlparse, parse_qsl, parse_qs
from django.conf import settings

# Create your views here.

class PortfolioGroupLV(ListView):
	model = Portfolio
	template_name = 'portfolio/portfolio_list.html'
	css_version = 17
	page_title = '포트폴리오 | '+settings.SITE_NAME

	def get_context_data(self, **kwargs):
		ctx = super(PortfolioGroupLV, self).get_context_data(**kwargs)
		ctx['category'] = 'portfolio'
		ctx['css_version'] = self.css_version
		ctx['page_title'] = self.page_title
		return ctx


class PortfolioGroupDV(DetailView):
	model = Portfolio
	template_name = 'portfolio/portfolio_detail.html'

	def get_context_data(self, **kwargs):
		ctx = super(PortfolioGroupDV, self).get_context_data(**kwargs)
		ctx['category'] = 'portfolio'
		ctx['css_version'] = PortfolioGroupLV.css_version
		ctx['youtube_content_id'] = get_youtube_content_id(self.object.link)
		ctx['page_title'] = PortfolioGroupLV.page_title
		return ctx


def get_youtube_content_id(url):
	a = urlparse(url)

	if 'www.youtube.com' in url:
		a = parse_qs(a.query)
		result = a['v'][0]
	else:
		result = a.path.replace('/', '')

	return result

portfolio/templates/portfolio/portfolio_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }} | {{ page_title }}{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/portfolio.css" %}?v={{ css_version }}{% endblock %}

{% load portfolio_filters %}
{% block content %}
<div class="bg bg1"></div>
<div id="content">
	<div class="portfolio-detail">
		<div class="portfolio-title">
			<div class="portfolio-thumbnail">
				<div class="line"></div>
				{% if object.image %}
	            <img class="thumbnail margin-5" src="{{ object.image.thumb_url }}" />
	            {% else %}
	            <img class="thumbnail margin-5" src="{{ object.link|youtube_thumb_url }}" onerror="this.src='{% static "images/default-picture.png"%}'" width="320" />
	            {% endif %}
			</div>
			<div class="portfolio-subject">
				<div class="line"></div>
				<span>{{ object.title }}</span>
				<!-- <div class="under-line"></div> -->
			</div>
		</div>

		<div class="description-row">
			<div class="description-title">DESCRIPTION</div>
			<div class="description">
				{{ object.description|linebreaks }}
			</div>
			{% if youtube_content_id %}
			<div class="movie">
				<iframe width="720" height="480" src="https://www.youtube.com/embed/{{youtube_content_id}}" frameborder="0" allowfullscreen></iframe>
			</div>
			{% endif %}			
		</div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/portfolio_list.html
{% extends "base.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/portfolio.css" %}?v={{ css_version }}{% endblock %}
{% load portfolio_filters %}
{% block content %}
<div class="bg bg1"></div>
<div id="content">
	<div class="portfolio">
		<!-- <div class="clear_float">
	        <h2 style="display:inline">{{ page_title }}</h2>
	    </div> -->
		<div class="album-list">
			{% for item in object_list %}
	        <div class="album-list-photo">
	            <a href="{{ item.get_absolute_url }}">
           		{% if item.image %}
	            <img class="thumbnail" src="{{ item.image.thumb_url }}" />
	            {% else %}
	            <img class="thumbnail" src="{{ item.link|youtube_thumb_url }}" onerror="this.src='{% static "images/default-picture.png"%}'" width="200" height="128" />
	            {% endif %}
	            </a>
	            <!-- <li class="title">{{ portfolio.title }}</li> -->
           		<!-- <li>{{ portfolio.description }}</li> -->
	        </div>
	        {% endfor %}
	    </div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/portfolio_list_year.html
{% extends "base.html" %}

{% block title %}포트폴리오{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/portfolio.css" %}{% endblock %}

{% block content %}
<style type="text/css">
	.portfolio{
		margin-left: 50px;
		margin-top: 50px;
	}
</style>
<div id="content">
	<div class="portfolio">


		<div class="clear_float">
	        <h2 style="display:inline"><a href="#">포트폴리오</a></h2>
	    </div>

		<div class="album-list">
			{% for item in object_list %}

			{% for portfolio in item.portfolio_set.all|slice:"5" %}
	        <div class="album-list-photo">
	            <a href="{{ portfolio.get_absolute_url }}">
	            <img class="thumbnail" src="{{ portfolio.image.thumb_url }}" />
	            </a>
	            <!-- <li class="title">{{ portfolio.title }}</li>
           		<li>{{ portfolio.description }}</li> -->
	        </div>
	        {% endfor %}
	        
	        {% endfor %}
	    </div>



    </div>
</div>
{% endblock %}