contents/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'contents'

urlpatterns = [
    # Example : /
    path('', ContentsLV.as_view(), name='index'),
    re_path('(?P<slug>[-\w]+)/$', ContentsDV.as_view(), name='detail'),
    # url(r'^portfolio-group/(?P<pk>\d+)/$', PortfolioGroupLV.as_view(), name='portfolio_group_detail'),
]

contents/models.py
from django.db import models
from django.urls import reverse
from portfolio.fields import ThumbnailImageField
from accounts.models import User
from django.utils.text import slugify
from portfolio.models import PortfolioGroup

# Create your models here.
class ContentsType(models.Model):
	name = models.CharField(max_length=50, null=True)
	description = models.CharField('설명', max_length=100, blank=True)

	class Meta:
		verbose_name_plural = '쉼표-타입'
		ordering = ['-name']

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('contents:detail', args=(self.id,))


class Contents(models.Model):
	group = models.ForeignKey(PortfolioGroup, verbose_name="년도", on_delete=models.CASCADE)
	contents_type = models.ForeignKey(ContentsType, verbose_name="타입", blank=True, null=True, on_delete=models.CASCADE)

	title = models.CharField('제목', max_length=50)
	slug = models.SlugField('SLUG', unique=True, allow_unicode=True, null=True, help_text='자동 입력')
	image = ThumbnailImageField(verbose_name="대표 이미지", upload_to='portfolio/%Y/%m', blank=True, null=True)
	description = models.TextField('DESCRIPTION', blank=True)
	link = models.URLField('link', blank=True)
	upload_date = models.DateTimeField('작성일', auto_now_add=True)
	user = models.ForeignKey(User, verbose_name="작성자", null=True, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = '쉼표'
		ordering = ['-upload_date']

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('contents:detail', args=(self.slug,))


	def save(self, *args, **kargs):
		if not self.id:
			self.slug = slugify(self.title, allow_unicode=True)
		super(Contents, self).save(*args, **kargs)

contents/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from contents.models import *
from portfolio.views import get_youtube_content_id, PortfolioGroupLV
from django.conf import settings

# Create your views here.

class ContentsLV(ListView):
	model = ContentsType
	template_name = 'contents/contents_list.html'
	css_version = PortfolioGroupLV.css_version
	page_title = '쉼표 | '+settings.SITE_NAME

	def get_context_data(self, **kwargs):
		ctx = super(ContentsLV, self).get_context_data(**kwargs)
		ctx['page_title'] = self.page_title
		ctx['category'] = 'contents'
		ctx['css_version'] = self.css_version
		return ctx


class ContentsDV(DetailView):
	model = Contents
	template_name = 'portfolio/portfolio_detail.html'

	def get_context_data(self, **kwargs):
		ctx = super(ContentsDV, self).get_context_data(**kwargs)
		ctx['page_title'] = ContentsLV.page_title
		ctx['category'] = 'contents'
		ctx['css_version'] = PortfolioGroupLV.css_version
		ctx['youtube_content_id'] = get_youtube_content_id(self.object.link)
		return ctx

contents/templates/contents/contents_list.html
{% extends "base.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/portfolio.css" %}?v={{ css_version }}{% endblock %}
{% load portfolio_filters %}
{% block content %}
<div class="bg bg1"></div>
<div id="content">
	<div class="portfolio">
		{% for item in object_list %}
		{% if item.contents_set.count > 0 %}
		<div class="clear_float list-title">
	        <h2 style="display:inline">{{ item.name }}</h2>
	    </div>
		<div class="album-list">
			{% for item_sub in item.contents_set.all %}
	        <div class="album-list-photo">
	            <a href="{{ item_sub.get_absolute_url }}">
           		{% if item_sub.image %}
	            <img class="thumbnail" src="{{ item_sub.image.thumb_url }}" />
	            {% else %}
	            <img class="thumbnail" src="{{ item_sub.link|youtube_thumb_url }}" onerror="this.src='{% static "images/default-picture.png" %}'" width="200" height="128" />
	            {% endif %}
	            </a>
	        </div>
	    	{% endfor %}
	    </div>
	    {% endif %}
	    {% endfor %}
    </div>
</div>
{% endblock %}