contents/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'contents'

urlpatterns = [
    # Example : /
    path('', ContentsLV.as_view(), name='index'),
    re_path('(?P<slug>[-\w]+)/$', ContentsDV.as_view(), name='detail'),
    # url(r'^portfolio-group/(?P<pk>\d+)/$', PortfolioGroupLV.as_view(), name='portfolio_group_detail'),
]

history/urls.py
# from django.conf.urls import url, include
from django.urls import path, include
from history.views import *

app_name = "history"

urlpatterns = [
    path('', historyIndex.as_view(), name='index'),
    # url(r'^test/', testIndex.as_view())
]

portfolio/urls.py
from django.urls import path, re_path
from portfolio.views import *
from django.http import HttpResponse

app_name = "portfolio"

urlpatterns = [
    path('', PortfolioGroupLV.as_view(), name='index'),
    re_path('(?P<slug>[\w-]+)/', PortfolioGroupDV.as_view(), name='portfolio_detail'),
    # path('<slug:slug>/', PortfolioGroupDV.as_view(), name='portfolio_detail'),
    # url(r'^portfolio-group/(?P<pk>\d+)/$', PortfolioGroupLV.as_view(), name='portfolio_group_detail'),
]

qna/urls.py
from django.urls import path
from qna.views import *

app_name = 'qna'

urlpatterns = [
    path('', qna_new.as_view(), name='index'),
    path('completion/', qnaComp.as_view(), name='comp'),
]

workflow/urls.py
from django.urls import path
from workflow.views import *

app_name = 'workflow';

urlpatterns = [
    path('', workflowIndex.as_view(), name='index'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
	<link rel="shortcut icon" href="/static/images/favicon.ico">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}?v=82">
	<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}">
</head>
<body>
{% if request.session.debug_mode %}
<style>
.debug{
	text-align: center;
	background: gray;
	padding: 5px;
	color: #FFF;
	font-weight: bold;
	background: linear-gradient(45deg, #8a8a8a 25%, #000000 0, #000000 50%, #8a8a8a 0, #8a8a8a 75%, #000000 0);
	-webkit-background-size: 20px 20px;
	background-size: 20px 20px;
	font-size: 12px;
}
</style>
<div class="debug">DEBUG MODE</div>
{% endif %}
<div class="header">
	<div class="header-row">
		<div class="logo">
			<a href="{% url 'index' %}"><div class="header-logo"></div></a>
		</div>
		<div class="header-menu">
			<div class="header-menu-sub {% if category in 'history' %}sel{% endif %}">
				<a href="{% url 'history:index' %}">History</a>
			</div>
			<div class="header-menu-sub {% if category in 'portfolio' %}sel{% endif %}">
				<a href="{% url 'portfolio:index' %}">Portfolio</a>
			</div>

			<div class="header-menu-sub {% if category in 'contents' %}sel{% endif %}">
				<a href="{% url 'contents:index' %}">쉼표</a>
			</div>
			<div class="header-menu-sub {% if category in 'workflow' %}sel{% endif %}">
				<a href="{% url 'workflow:index' %}">Workflow</a>
			</div>
			<div class="header-menu-sub {% if category in 'qna' %}sel{% endif %}">
				<a href="{% url 'qna:index' %}">Q&amp;A</a>
			</div>
		</div>
	</div>
	<div class="mobile-header-row">
		<div class="mobile-header-bg"></div>
		<div class="logo">
			<a href="{% url 'index' %}"><div class="logo-img">{ LOGO IMAGE }</div></a>
		</div>
		<label for="toggle"></label>
		<div class="menu-btn" id="header-menu-btn"></div>
		<div class="menu-btn-row" id="mobile-header-menu">
			<a href="{% url 'history:index' %}"><div class="mobile-menu-sub">History</div></a>
			<a href="{% url 'portfolio:index' %}"><div class="mobile-menu-sub">Portfolio</div></a>
			<a href="{% url 'contents:index' %}"><div class="mobile-menu-sub">쉼표</div></a>
			<a href="{% url 'workflow:index' %}"><div class="mobile-menu-sub">Workflow</div></a>
			<a href="{% url 'qna:index' %}"><div class="mobile-menu-sub">Q&amp;A</div></a>
		</div>
	</div>
</div>
{% block content %}{% endblock %}
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
<div id="footer">
	<div class="footer-background"></div>
	<span>Copyright 2015-{% now 'Y' %} Goodboy Pictures All Rights Reserved</span>
</div>
</body>
<!-- <script src="https://statistics.jhje.co.kr/inflow.js"></script> -->
</html>

templates/google2e14cadb121fa19f.html
google-site-verification: google2e14cadb121fa19f.html

templates/home.html
{% extends "base.html" %}

{% block title %}굿보이 픽쳐스{% endblock %}

{% block content %}
<div class="bg bg1"></div>
<div id="content">
	<div class="main">
		<div class="main-logo"></div>
		<div class="introduce">
			    성장하는 영화영상제작사 {% if request.user_agent.is_mobile %}<br>{% endif %}굿보이픽쳐스 입니다.
		</div>
	</div>
</div>
{% endblock content %}

templates/instagram.html
{% extends "base.html" %}

{% block title %}굿보이 픽쳐스{% endblock %}

{% block content %}
<div class="bg bg1"></div>
<div id="content">
	<div class="main">
		<div class="main-logo"></div>
		<div class="introduce">
			성장하는 영화영상제작사 {% if request.user_agent.is_mobile %}<br>{% endif %}굿보이픽쳐스 입니다.
		</div>
		<div class="instagram-area">
			<div class="instagram-user">
				<div class="picture">
					<img src="{{ instagram_user.data.profile_picture }}" alt="">
				</div>
				<div class="description">
					<div class="username">{{ instagram_user.data.username }}</div>
					<div class="user-info">
						<span>게시물 {{ instagram_user.data.counts.media }}</span>
						<span>팔로워 {{ instagram_user.data.counts.followed_by }}</span>
						<span>팔로우 {{ instagram_user.data.counts.follows }}</span>
					</div>
					<div class="bio">{% autoescape off %}{{ instagram_bio }}{% endautoescape %}&nbsp;<a href="{{ instagram_user.data.website }}" target="_blank">{{ instagram_user.data.website }}</a></div>
				</div>
			</div>
			<div class="instagram-media">
				{% for item in instagram_media.data %}
				<div style="position: relative;">
					<a href="{{ item.link }}" target="_blank">
						<div class="instagram-thumbnail">
							<img src="{{ item.images.thumbnail.url }}">
							<div class="media-info" style="position: absolute; top: 0;">
								<span class="insta-icon insta-likes">{{ item.likes.count }}</span>
								<span class="insta-icon insta-comments">{{ item.comments.count }}</span>
							</div>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% load staticfiles %}
<script type="text/javascript" src="{% static 'js/instagram.js' %}"></script>
{% endblock content %}

templates/naverfd1ec1a5e2333b4bc525448f1417a65f.html
naver-site-verification: naverfd1ec1a5e2333b4bc525448f1417a65f.html